// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: org/bedu/postworksone/protos/Doctor.proto

package org.bedu.postworksone.protos.models;

public final class DoctorProto {
  private DoctorProto() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  public interface DoctorOrBuilder extends
      // @@protoc_insertion_point(interface_extends:postwork.Doctor)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>required string id = 1;</code>
     * @return Whether the id field is set.
     */
    boolean hasId();
    /**
     * <code>required string id = 1;</code>
     * @return The id.
     */
    java.lang.String getId();
    /**
     * <code>required string id = 1;</code>
     * @return The bytes for id.
     */
    com.google.protobuf.ByteString
        getIdBytes();

    /**
     * <code>required string name = 2;</code>
     * @return Whether the name field is set.
     */
    boolean hasName();
    /**
     * <code>required string name = 2;</code>
     * @return The name.
     */
    java.lang.String getName();
    /**
     * <code>required string name = 2;</code>
     * @return The bytes for name.
     */
    com.google.protobuf.ByteString
        getNameBytes();

    /**
     * <code>required string lastname = 3;</code>
     * @return Whether the lastname field is set.
     */
    boolean hasLastname();
    /**
     * <code>required string lastname = 3;</code>
     * @return The lastname.
     */
    java.lang.String getLastname();
    /**
     * <code>required string lastname = 3;</code>
     * @return The bytes for lastname.
     */
    com.google.protobuf.ByteString
        getLastnameBytes();

    /**
     * <code>required string birthday = 4;</code>
     * @return Whether the birthday field is set.
     */
    boolean hasBirthday();
    /**
     * <code>required string birthday = 4;</code>
     * @return The birthday.
     */
    java.lang.String getBirthday();
    /**
     * <code>required string birthday = 4;</code>
     * @return The bytes for birthday.
     */
    com.google.protobuf.ByteString
        getBirthdayBytes();

    /**
     * <code>required bool specialized = 5;</code>
     * @return Whether the specialized field is set.
     */
    boolean hasSpecialized();
    /**
     * <code>required bool specialized = 5;</code>
     * @return The specialized.
     */
    boolean getSpecialized();

    /**
     * <code>optional string speciality = 6;</code>
     * @return Whether the speciality field is set.
     */
    boolean hasSpeciality();
    /**
     * <code>optional string speciality = 6;</code>
     * @return The speciality.
     */
    java.lang.String getSpeciality();
    /**
     * <code>optional string speciality = 6;</code>
     * @return The bytes for speciality.
     */
    com.google.protobuf.ByteString
        getSpecialityBytes();

    /**
     * <code>required int32 yearsExperience = 7;</code>
     * @return Whether the yearsExperience field is set.
     */
    boolean hasYearsExperience();
    /**
     * <code>required int32 yearsExperience = 7;</code>
     * @return The yearsExperience.
     */
    int getYearsExperience();
  }
  /**
   * Protobuf type {@code postwork.Doctor}
   */
  public  static final class Doctor extends
      com.google.protobuf.GeneratedMessageV3 implements
      // @@protoc_insertion_point(message_implements:postwork.Doctor)
      DoctorOrBuilder {
  private static final long serialVersionUID = 0L;
    // Use Doctor.newBuilder() to construct.
    private Doctor(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
      super(builder);
    }
    private Doctor() {
      id_ = "";
      name_ = "";
      lastname_ = "";
      birthday_ = "";
      speciality_ = "";
    }

    @java.lang.Override
    @SuppressWarnings({"unused"})
    protected java.lang.Object newInstance(
        UnusedPrivateParameter unused) {
      return new Doctor();
    }

    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
    getUnknownFields() {
      return this.unknownFields;
    }
    private Doctor(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      this();
      if (extensionRegistry == null) {
        throw new java.lang.NullPointerException();
      }
      int mutable_bitField0_ = 0;
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            case 10: {
              com.google.protobuf.ByteString bs = input.readBytes();
              bitField0_ |= 0x00000001;
              id_ = bs;
              break;
            }
            case 18: {
              com.google.protobuf.ByteString bs = input.readBytes();
              bitField0_ |= 0x00000002;
              name_ = bs;
              break;
            }
            case 26: {
              com.google.protobuf.ByteString bs = input.readBytes();
              bitField0_ |= 0x00000004;
              lastname_ = bs;
              break;
            }
            case 34: {
              com.google.protobuf.ByteString bs = input.readBytes();
              bitField0_ |= 0x00000008;
              birthday_ = bs;
              break;
            }
            case 40: {
              bitField0_ |= 0x00000010;
              specialized_ = input.readBool();
              break;
            }
            case 50: {
              com.google.protobuf.ByteString bs = input.readBytes();
              bitField0_ |= 0x00000020;
              speciality_ = bs;
              break;
            }
            case 56: {
              bitField0_ |= 0x00000040;
              yearsExperience_ = input.readInt32();
              break;
            }
            default: {
              if (!parseUnknownField(
                  input, unknownFields, extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e).setUnfinishedMessage(this);
      } finally {
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return org.bedu.postworksone.protos.models.DoctorProto.internal_static_postwork_Doctor_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return org.bedu.postworksone.protos.models.DoctorProto.internal_static_postwork_Doctor_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              org.bedu.postworksone.protos.models.DoctorProto.Doctor.class, org.bedu.postworksone.protos.models.DoctorProto.Doctor.Builder.class);
    }

    private int bitField0_;
    public static final int ID_FIELD_NUMBER = 1;
    private volatile java.lang.Object id_;
    /**
     * <code>required string id = 1;</code>
     * @return Whether the id field is set.
     */
    public boolean hasId() {
      return ((bitField0_ & 0x00000001) != 0);
    }
    /**
     * <code>required string id = 1;</code>
     * @return The id.
     */
    public java.lang.String getId() {
      java.lang.Object ref = id_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        if (bs.isValidUtf8()) {
          id_ = s;
        }
        return s;
      }
    }
    /**
     * <code>required string id = 1;</code>
     * @return The bytes for id.
     */
    public com.google.protobuf.ByteString
        getIdBytes() {
      java.lang.Object ref = id_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        id_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int NAME_FIELD_NUMBER = 2;
    private volatile java.lang.Object name_;
    /**
     * <code>required string name = 2;</code>
     * @return Whether the name field is set.
     */
    public boolean hasName() {
      return ((bitField0_ & 0x00000002) != 0);
    }
    /**
     * <code>required string name = 2;</code>
     * @return The name.
     */
    public java.lang.String getName() {
      java.lang.Object ref = name_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        if (bs.isValidUtf8()) {
          name_ = s;
        }
        return s;
      }
    }
    /**
     * <code>required string name = 2;</code>
     * @return The bytes for name.
     */
    public com.google.protobuf.ByteString
        getNameBytes() {
      java.lang.Object ref = name_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        name_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int LASTNAME_FIELD_NUMBER = 3;
    private volatile java.lang.Object lastname_;
    /**
     * <code>required string lastname = 3;</code>
     * @return Whether the lastname field is set.
     */
    public boolean hasLastname() {
      return ((bitField0_ & 0x00000004) != 0);
    }
    /**
     * <code>required string lastname = 3;</code>
     * @return The lastname.
     */
    public java.lang.String getLastname() {
      java.lang.Object ref = lastname_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        if (bs.isValidUtf8()) {
          lastname_ = s;
        }
        return s;
      }
    }
    /**
     * <code>required string lastname = 3;</code>
     * @return The bytes for lastname.
     */
    public com.google.protobuf.ByteString
        getLastnameBytes() {
      java.lang.Object ref = lastname_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        lastname_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int BIRTHDAY_FIELD_NUMBER = 4;
    private volatile java.lang.Object birthday_;
    /**
     * <code>required string birthday = 4;</code>
     * @return Whether the birthday field is set.
     */
    public boolean hasBirthday() {
      return ((bitField0_ & 0x00000008) != 0);
    }
    /**
     * <code>required string birthday = 4;</code>
     * @return The birthday.
     */
    public java.lang.String getBirthday() {
      java.lang.Object ref = birthday_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        if (bs.isValidUtf8()) {
          birthday_ = s;
        }
        return s;
      }
    }
    /**
     * <code>required string birthday = 4;</code>
     * @return The bytes for birthday.
     */
    public com.google.protobuf.ByteString
        getBirthdayBytes() {
      java.lang.Object ref = birthday_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        birthday_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int SPECIALIZED_FIELD_NUMBER = 5;
    private boolean specialized_;
    /**
     * <code>required bool specialized = 5;</code>
     * @return Whether the specialized field is set.
     */
    public boolean hasSpecialized() {
      return ((bitField0_ & 0x00000010) != 0);
    }
    /**
     * <code>required bool specialized = 5;</code>
     * @return The specialized.
     */
    public boolean getSpecialized() {
      return specialized_;
    }

    public static final int SPECIALITY_FIELD_NUMBER = 6;
    private volatile java.lang.Object speciality_;
    /**
     * <code>optional string speciality = 6;</code>
     * @return Whether the speciality field is set.
     */
    public boolean hasSpeciality() {
      return ((bitField0_ & 0x00000020) != 0);
    }
    /**
     * <code>optional string speciality = 6;</code>
     * @return The speciality.
     */
    public java.lang.String getSpeciality() {
      java.lang.Object ref = speciality_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        if (bs.isValidUtf8()) {
          speciality_ = s;
        }
        return s;
      }
    }
    /**
     * <code>optional string speciality = 6;</code>
     * @return The bytes for speciality.
     */
    public com.google.protobuf.ByteString
        getSpecialityBytes() {
      java.lang.Object ref = speciality_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        speciality_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int YEARSEXPERIENCE_FIELD_NUMBER = 7;
    private int yearsExperience_;
    /**
     * <code>required int32 yearsExperience = 7;</code>
     * @return Whether the yearsExperience field is set.
     */
    public boolean hasYearsExperience() {
      return ((bitField0_ & 0x00000040) != 0);
    }
    /**
     * <code>required int32 yearsExperience = 7;</code>
     * @return The yearsExperience.
     */
    public int getYearsExperience() {
      return yearsExperience_;
    }

    private byte memoizedIsInitialized = -1;
    @java.lang.Override
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      if (!hasId()) {
        memoizedIsInitialized = 0;
        return false;
      }
      if (!hasName()) {
        memoizedIsInitialized = 0;
        return false;
      }
      if (!hasLastname()) {
        memoizedIsInitialized = 0;
        return false;
      }
      if (!hasBirthday()) {
        memoizedIsInitialized = 0;
        return false;
      }
      if (!hasSpecialized()) {
        memoizedIsInitialized = 0;
        return false;
      }
      if (!hasYearsExperience()) {
        memoizedIsInitialized = 0;
        return false;
      }
      memoizedIsInitialized = 1;
      return true;
    }

    @java.lang.Override
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      if (((bitField0_ & 0x00000001) != 0)) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 1, id_);
      }
      if (((bitField0_ & 0x00000002) != 0)) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 2, name_);
      }
      if (((bitField0_ & 0x00000004) != 0)) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 3, lastname_);
      }
      if (((bitField0_ & 0x00000008) != 0)) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 4, birthday_);
      }
      if (((bitField0_ & 0x00000010) != 0)) {
        output.writeBool(5, specialized_);
      }
      if (((bitField0_ & 0x00000020) != 0)) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 6, speciality_);
      }
      if (((bitField0_ & 0x00000040) != 0)) {
        output.writeInt32(7, yearsExperience_);
      }
      unknownFields.writeTo(output);
    }

    @java.lang.Override
    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      if (((bitField0_ & 0x00000001) != 0)) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(1, id_);
      }
      if (((bitField0_ & 0x00000002) != 0)) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(2, name_);
      }
      if (((bitField0_ & 0x00000004) != 0)) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(3, lastname_);
      }
      if (((bitField0_ & 0x00000008) != 0)) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(4, birthday_);
      }
      if (((bitField0_ & 0x00000010) != 0)) {
        size += com.google.protobuf.CodedOutputStream
          .computeBoolSize(5, specialized_);
      }
      if (((bitField0_ & 0x00000020) != 0)) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(6, speciality_);
      }
      if (((bitField0_ & 0x00000040) != 0)) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(7, yearsExperience_);
      }
      size += unknownFields.getSerializedSize();
      memoizedSize = size;
      return size;
    }

    @java.lang.Override
    public boolean equals(final java.lang.Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof org.bedu.postworksone.protos.models.DoctorProto.Doctor)) {
        return super.equals(obj);
      }
      org.bedu.postworksone.protos.models.DoctorProto.Doctor other = (org.bedu.postworksone.protos.models.DoctorProto.Doctor) obj;

      if (hasId() != other.hasId()) return false;
      if (hasId()) {
        if (!getId()
            .equals(other.getId())) return false;
      }
      if (hasName() != other.hasName()) return false;
      if (hasName()) {
        if (!getName()
            .equals(other.getName())) return false;
      }
      if (hasLastname() != other.hasLastname()) return false;
      if (hasLastname()) {
        if (!getLastname()
            .equals(other.getLastname())) return false;
      }
      if (hasBirthday() != other.hasBirthday()) return false;
      if (hasBirthday()) {
        if (!getBirthday()
            .equals(other.getBirthday())) return false;
      }
      if (hasSpecialized() != other.hasSpecialized()) return false;
      if (hasSpecialized()) {
        if (getSpecialized()
            != other.getSpecialized()) return false;
      }
      if (hasSpeciality() != other.hasSpeciality()) return false;
      if (hasSpeciality()) {
        if (!getSpeciality()
            .equals(other.getSpeciality())) return false;
      }
      if (hasYearsExperience() != other.hasYearsExperience()) return false;
      if (hasYearsExperience()) {
        if (getYearsExperience()
            != other.getYearsExperience()) return false;
      }
      if (!unknownFields.equals(other.unknownFields)) return false;
      return true;
    }

    @java.lang.Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptor().hashCode();
      if (hasId()) {
        hash = (37 * hash) + ID_FIELD_NUMBER;
        hash = (53 * hash) + getId().hashCode();
      }
      if (hasName()) {
        hash = (37 * hash) + NAME_FIELD_NUMBER;
        hash = (53 * hash) + getName().hashCode();
      }
      if (hasLastname()) {
        hash = (37 * hash) + LASTNAME_FIELD_NUMBER;
        hash = (53 * hash) + getLastname().hashCode();
      }
      if (hasBirthday()) {
        hash = (37 * hash) + BIRTHDAY_FIELD_NUMBER;
        hash = (53 * hash) + getBirthday().hashCode();
      }
      if (hasSpecialized()) {
        hash = (37 * hash) + SPECIALIZED_FIELD_NUMBER;
        hash = (53 * hash) + com.google.protobuf.Internal.hashBoolean(
            getSpecialized());
      }
      if (hasSpeciality()) {
        hash = (37 * hash) + SPECIALITY_FIELD_NUMBER;
        hash = (53 * hash) + getSpeciality().hashCode();
      }
      if (hasYearsExperience()) {
        hash = (37 * hash) + YEARSEXPERIENCE_FIELD_NUMBER;
        hash = (53 * hash) + getYearsExperience();
      }
      hash = (29 * hash) + unknownFields.hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static org.bedu.postworksone.protos.models.DoctorProto.Doctor parseFrom(
        java.nio.ByteBuffer data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static org.bedu.postworksone.protos.models.DoctorProto.Doctor parseFrom(
        java.nio.ByteBuffer data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static org.bedu.postworksone.protos.models.DoctorProto.Doctor parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static org.bedu.postworksone.protos.models.DoctorProto.Doctor parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static org.bedu.postworksone.protos.models.DoctorProto.Doctor parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static org.bedu.postworksone.protos.models.DoctorProto.Doctor parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static org.bedu.postworksone.protos.models.DoctorProto.Doctor parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static org.bedu.postworksone.protos.models.DoctorProto.Doctor parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }
    public static org.bedu.postworksone.protos.models.DoctorProto.Doctor parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input);
    }
    public static org.bedu.postworksone.protos.models.DoctorProto.Doctor parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static org.bedu.postworksone.protos.models.DoctorProto.Doctor parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static org.bedu.postworksone.protos.models.DoctorProto.Doctor parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    @java.lang.Override
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(org.bedu.postworksone.protos.models.DoctorProto.Doctor prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    @java.lang.Override
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code postwork.Doctor}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:postwork.Doctor)
        org.bedu.postworksone.protos.models.DoctorProto.DoctorOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return org.bedu.postworksone.protos.models.DoctorProto.internal_static_postwork_Doctor_descriptor;
      }

      @java.lang.Override
      protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return org.bedu.postworksone.protos.models.DoctorProto.internal_static_postwork_Doctor_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                org.bedu.postworksone.protos.models.DoctorProto.Doctor.class, org.bedu.postworksone.protos.models.DoctorProto.Doctor.Builder.class);
      }

      // Construct using org.bedu.postworksone.protos.models.DoctorProto.Doctor.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessageV3
                .alwaysUseFieldBuilders) {
        }
      }
      @java.lang.Override
      public Builder clear() {
        super.clear();
        id_ = "";
        bitField0_ = (bitField0_ & ~0x00000001);
        name_ = "";
        bitField0_ = (bitField0_ & ~0x00000002);
        lastname_ = "";
        bitField0_ = (bitField0_ & ~0x00000004);
        birthday_ = "";
        bitField0_ = (bitField0_ & ~0x00000008);
        specialized_ = false;
        bitField0_ = (bitField0_ & ~0x00000010);
        speciality_ = "";
        bitField0_ = (bitField0_ & ~0x00000020);
        yearsExperience_ = 0;
        bitField0_ = (bitField0_ & ~0x00000040);
        return this;
      }

      @java.lang.Override
      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return org.bedu.postworksone.protos.models.DoctorProto.internal_static_postwork_Doctor_descriptor;
      }

      @java.lang.Override
      public org.bedu.postworksone.protos.models.DoctorProto.Doctor getDefaultInstanceForType() {
        return org.bedu.postworksone.protos.models.DoctorProto.Doctor.getDefaultInstance();
      }

      @java.lang.Override
      public org.bedu.postworksone.protos.models.DoctorProto.Doctor build() {
        org.bedu.postworksone.protos.models.DoctorProto.Doctor result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      @java.lang.Override
      public org.bedu.postworksone.protos.models.DoctorProto.Doctor buildPartial() {
        org.bedu.postworksone.protos.models.DoctorProto.Doctor result = new org.bedu.postworksone.protos.models.DoctorProto.Doctor(this);
        int from_bitField0_ = bitField0_;
        int to_bitField0_ = 0;
        if (((from_bitField0_ & 0x00000001) != 0)) {
          to_bitField0_ |= 0x00000001;
        }
        result.id_ = id_;
        if (((from_bitField0_ & 0x00000002) != 0)) {
          to_bitField0_ |= 0x00000002;
        }
        result.name_ = name_;
        if (((from_bitField0_ & 0x00000004) != 0)) {
          to_bitField0_ |= 0x00000004;
        }
        result.lastname_ = lastname_;
        if (((from_bitField0_ & 0x00000008) != 0)) {
          to_bitField0_ |= 0x00000008;
        }
        result.birthday_ = birthday_;
        if (((from_bitField0_ & 0x00000010) != 0)) {
          result.specialized_ = specialized_;
          to_bitField0_ |= 0x00000010;
        }
        if (((from_bitField0_ & 0x00000020) != 0)) {
          to_bitField0_ |= 0x00000020;
        }
        result.speciality_ = speciality_;
        if (((from_bitField0_ & 0x00000040) != 0)) {
          result.yearsExperience_ = yearsExperience_;
          to_bitField0_ |= 0x00000040;
        }
        result.bitField0_ = to_bitField0_;
        onBuilt();
        return result;
      }

      @java.lang.Override
      public Builder clone() {
        return super.clone();
      }
      @java.lang.Override
      public Builder setField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return super.setField(field, value);
      }
      @java.lang.Override
      public Builder clearField(
          com.google.protobuf.Descriptors.FieldDescriptor field) {
        return super.clearField(field);
      }
      @java.lang.Override
      public Builder clearOneof(
          com.google.protobuf.Descriptors.OneofDescriptor oneof) {
        return super.clearOneof(oneof);
      }
      @java.lang.Override
      public Builder setRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          int index, java.lang.Object value) {
        return super.setRepeatedField(field, index, value);
      }
      @java.lang.Override
      public Builder addRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return super.addRepeatedField(field, value);
      }
      @java.lang.Override
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof org.bedu.postworksone.protos.models.DoctorProto.Doctor) {
          return mergeFrom((org.bedu.postworksone.protos.models.DoctorProto.Doctor)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(org.bedu.postworksone.protos.models.DoctorProto.Doctor other) {
        if (other == org.bedu.postworksone.protos.models.DoctorProto.Doctor.getDefaultInstance()) return this;
        if (other.hasId()) {
          bitField0_ |= 0x00000001;
          id_ = other.id_;
          onChanged();
        }
        if (other.hasName()) {
          bitField0_ |= 0x00000002;
          name_ = other.name_;
          onChanged();
        }
        if (other.hasLastname()) {
          bitField0_ |= 0x00000004;
          lastname_ = other.lastname_;
          onChanged();
        }
        if (other.hasBirthday()) {
          bitField0_ |= 0x00000008;
          birthday_ = other.birthday_;
          onChanged();
        }
        if (other.hasSpecialized()) {
          setSpecialized(other.getSpecialized());
        }
        if (other.hasSpeciality()) {
          bitField0_ |= 0x00000020;
          speciality_ = other.speciality_;
          onChanged();
        }
        if (other.hasYearsExperience()) {
          setYearsExperience(other.getYearsExperience());
        }
        this.mergeUnknownFields(other.unknownFields);
        onChanged();
        return this;
      }

      @java.lang.Override
      public final boolean isInitialized() {
        if (!hasId()) {
          return false;
        }
        if (!hasName()) {
          return false;
        }
        if (!hasLastname()) {
          return false;
        }
        if (!hasBirthday()) {
          return false;
        }
        if (!hasSpecialized()) {
          return false;
        }
        if (!hasYearsExperience()) {
          return false;
        }
        return true;
      }

      @java.lang.Override
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        org.bedu.postworksone.protos.models.DoctorProto.Doctor parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (org.bedu.postworksone.protos.models.DoctorProto.Doctor) e.getUnfinishedMessage();
          throw e.unwrapIOException();
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }
      private int bitField0_;

      private java.lang.Object id_ = "";
      /**
       * <code>required string id = 1;</code>
       * @return Whether the id field is set.
       */
      public boolean hasId() {
        return ((bitField0_ & 0x00000001) != 0);
      }
      /**
       * <code>required string id = 1;</code>
       * @return The id.
       */
      public java.lang.String getId() {
        java.lang.Object ref = id_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          if (bs.isValidUtf8()) {
            id_ = s;
          }
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>required string id = 1;</code>
       * @return The bytes for id.
       */
      public com.google.protobuf.ByteString
          getIdBytes() {
        java.lang.Object ref = id_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          id_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>required string id = 1;</code>
       * @param value The id to set.
       * @return This builder for chaining.
       */
      public Builder setId(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000001;
        id_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>required string id = 1;</code>
       * @return This builder for chaining.
       */
      public Builder clearId() {
        bitField0_ = (bitField0_ & ~0x00000001);
        id_ = getDefaultInstance().getId();
        onChanged();
        return this;
      }
      /**
       * <code>required string id = 1;</code>
       * @param value The bytes for id to set.
       * @return This builder for chaining.
       */
      public Builder setIdBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000001;
        id_ = value;
        onChanged();
        return this;
      }

      private java.lang.Object name_ = "";
      /**
       * <code>required string name = 2;</code>
       * @return Whether the name field is set.
       */
      public boolean hasName() {
        return ((bitField0_ & 0x00000002) != 0);
      }
      /**
       * <code>required string name = 2;</code>
       * @return The name.
       */
      public java.lang.String getName() {
        java.lang.Object ref = name_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          if (bs.isValidUtf8()) {
            name_ = s;
          }
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>required string name = 2;</code>
       * @return The bytes for name.
       */
      public com.google.protobuf.ByteString
          getNameBytes() {
        java.lang.Object ref = name_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          name_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>required string name = 2;</code>
       * @param value The name to set.
       * @return This builder for chaining.
       */
      public Builder setName(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000002;
        name_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>required string name = 2;</code>
       * @return This builder for chaining.
       */
      public Builder clearName() {
        bitField0_ = (bitField0_ & ~0x00000002);
        name_ = getDefaultInstance().getName();
        onChanged();
        return this;
      }
      /**
       * <code>required string name = 2;</code>
       * @param value The bytes for name to set.
       * @return This builder for chaining.
       */
      public Builder setNameBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000002;
        name_ = value;
        onChanged();
        return this;
      }

      private java.lang.Object lastname_ = "";
      /**
       * <code>required string lastname = 3;</code>
       * @return Whether the lastname field is set.
       */
      public boolean hasLastname() {
        return ((bitField0_ & 0x00000004) != 0);
      }
      /**
       * <code>required string lastname = 3;</code>
       * @return The lastname.
       */
      public java.lang.String getLastname() {
        java.lang.Object ref = lastname_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          if (bs.isValidUtf8()) {
            lastname_ = s;
          }
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>required string lastname = 3;</code>
       * @return The bytes for lastname.
       */
      public com.google.protobuf.ByteString
          getLastnameBytes() {
        java.lang.Object ref = lastname_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          lastname_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>required string lastname = 3;</code>
       * @param value The lastname to set.
       * @return This builder for chaining.
       */
      public Builder setLastname(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000004;
        lastname_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>required string lastname = 3;</code>
       * @return This builder for chaining.
       */
      public Builder clearLastname() {
        bitField0_ = (bitField0_ & ~0x00000004);
        lastname_ = getDefaultInstance().getLastname();
        onChanged();
        return this;
      }
      /**
       * <code>required string lastname = 3;</code>
       * @param value The bytes for lastname to set.
       * @return This builder for chaining.
       */
      public Builder setLastnameBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000004;
        lastname_ = value;
        onChanged();
        return this;
      }

      private java.lang.Object birthday_ = "";
      /**
       * <code>required string birthday = 4;</code>
       * @return Whether the birthday field is set.
       */
      public boolean hasBirthday() {
        return ((bitField0_ & 0x00000008) != 0);
      }
      /**
       * <code>required string birthday = 4;</code>
       * @return The birthday.
       */
      public java.lang.String getBirthday() {
        java.lang.Object ref = birthday_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          if (bs.isValidUtf8()) {
            birthday_ = s;
          }
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>required string birthday = 4;</code>
       * @return The bytes for birthday.
       */
      public com.google.protobuf.ByteString
          getBirthdayBytes() {
        java.lang.Object ref = birthday_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          birthday_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>required string birthday = 4;</code>
       * @param value The birthday to set.
       * @return This builder for chaining.
       */
      public Builder setBirthday(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000008;
        birthday_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>required string birthday = 4;</code>
       * @return This builder for chaining.
       */
      public Builder clearBirthday() {
        bitField0_ = (bitField0_ & ~0x00000008);
        birthday_ = getDefaultInstance().getBirthday();
        onChanged();
        return this;
      }
      /**
       * <code>required string birthday = 4;</code>
       * @param value The bytes for birthday to set.
       * @return This builder for chaining.
       */
      public Builder setBirthdayBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000008;
        birthday_ = value;
        onChanged();
        return this;
      }

      private boolean specialized_ ;
      /**
       * <code>required bool specialized = 5;</code>
       * @return Whether the specialized field is set.
       */
      public boolean hasSpecialized() {
        return ((bitField0_ & 0x00000010) != 0);
      }
      /**
       * <code>required bool specialized = 5;</code>
       * @return The specialized.
       */
      public boolean getSpecialized() {
        return specialized_;
      }
      /**
       * <code>required bool specialized = 5;</code>
       * @param value The specialized to set.
       * @return This builder for chaining.
       */
      public Builder setSpecialized(boolean value) {
        bitField0_ |= 0x00000010;
        specialized_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>required bool specialized = 5;</code>
       * @return This builder for chaining.
       */
      public Builder clearSpecialized() {
        bitField0_ = (bitField0_ & ~0x00000010);
        specialized_ = false;
        onChanged();
        return this;
      }

      private java.lang.Object speciality_ = "";
      /**
       * <code>optional string speciality = 6;</code>
       * @return Whether the speciality field is set.
       */
      public boolean hasSpeciality() {
        return ((bitField0_ & 0x00000020) != 0);
      }
      /**
       * <code>optional string speciality = 6;</code>
       * @return The speciality.
       */
      public java.lang.String getSpeciality() {
        java.lang.Object ref = speciality_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          if (bs.isValidUtf8()) {
            speciality_ = s;
          }
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>optional string speciality = 6;</code>
       * @return The bytes for speciality.
       */
      public com.google.protobuf.ByteString
          getSpecialityBytes() {
        java.lang.Object ref = speciality_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          speciality_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>optional string speciality = 6;</code>
       * @param value The speciality to set.
       * @return This builder for chaining.
       */
      public Builder setSpeciality(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000020;
        speciality_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional string speciality = 6;</code>
       * @return This builder for chaining.
       */
      public Builder clearSpeciality() {
        bitField0_ = (bitField0_ & ~0x00000020);
        speciality_ = getDefaultInstance().getSpeciality();
        onChanged();
        return this;
      }
      /**
       * <code>optional string speciality = 6;</code>
       * @param value The bytes for speciality to set.
       * @return This builder for chaining.
       */
      public Builder setSpecialityBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000020;
        speciality_ = value;
        onChanged();
        return this;
      }

      private int yearsExperience_ ;
      /**
       * <code>required int32 yearsExperience = 7;</code>
       * @return Whether the yearsExperience field is set.
       */
      public boolean hasYearsExperience() {
        return ((bitField0_ & 0x00000040) != 0);
      }
      /**
       * <code>required int32 yearsExperience = 7;</code>
       * @return The yearsExperience.
       */
      public int getYearsExperience() {
        return yearsExperience_;
      }
      /**
       * <code>required int32 yearsExperience = 7;</code>
       * @param value The yearsExperience to set.
       * @return This builder for chaining.
       */
      public Builder setYearsExperience(int value) {
        bitField0_ |= 0x00000040;
        yearsExperience_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>required int32 yearsExperience = 7;</code>
       * @return This builder for chaining.
       */
      public Builder clearYearsExperience() {
        bitField0_ = (bitField0_ & ~0x00000040);
        yearsExperience_ = 0;
        onChanged();
        return this;
      }
      @java.lang.Override
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.setUnknownFields(unknownFields);
      }

      @java.lang.Override
      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.mergeUnknownFields(unknownFields);
      }


      // @@protoc_insertion_point(builder_scope:postwork.Doctor)
    }

    // @@protoc_insertion_point(class_scope:postwork.Doctor)
    private static final org.bedu.postworksone.protos.models.DoctorProto.Doctor DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new org.bedu.postworksone.protos.models.DoctorProto.Doctor();
    }

    public static org.bedu.postworksone.protos.models.DoctorProto.Doctor getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    @java.lang.Deprecated public static final com.google.protobuf.Parser<Doctor>
        PARSER = new com.google.protobuf.AbstractParser<Doctor>() {
      @java.lang.Override
      public Doctor parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new Doctor(input, extensionRegistry);
      }
    };

    public static com.google.protobuf.Parser<Doctor> parser() {
      return PARSER;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<Doctor> getParserForType() {
      return PARSER;
    }

    @java.lang.Override
    public org.bedu.postworksone.protos.models.DoctorProto.Doctor getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_postwork_Doctor_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_postwork_Doctor_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n)org/bedu/postworksone/protos/Doctor.pr" +
      "oto\022\010postwork\"\210\001\n\006Doctor\022\n\n\002id\030\001 \002(\t\022\014\n\004" +
      "name\030\002 \002(\t\022\020\n\010lastname\030\003 \002(\t\022\020\n\010birthday" +
      "\030\004 \002(\t\022\023\n\013specialized\030\005 \002(\010\022\022\n\nspecialit" +
      "y\030\006 \001(\t\022\027\n\017yearsExperience\030\007 \002(\005B2\n#org." +
      "bedu.postworksone.protos.modelsB\013DoctorP" +
      "roto"
    };
    descriptor = com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        });
    internal_static_postwork_Doctor_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_postwork_Doctor_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_postwork_Doctor_descriptor,
        new java.lang.String[] { "Id", "Name", "Lastname", "Birthday", "Specialized", "Speciality", "YearsExperience", });
  }

  // @@protoc_insertion_point(outer_class_scope)
}
